---
- name: Create GitHub Actions Runner w/ Ansible
  become: true
  gather_facts: true
  hosts: all

  vars:
    github_account: "{{lookup('ansible.builtin.env','GITHUB_ACCOUNT')}}"
    github_repo: "{{lookup('ansible.builtin.env','GITHUB_REPO')}}"
    user_management:
      - name: runner
        comment: GitHub Actions runner account
        shell: /bin/bash
        groups:
          - sudo
        system: yes
    hide_sensitive_logs: true
    packages:
      - gcc
      - libffi-devel
      - openssh-clients
      - git
      - yum-utils
      - python3
      - python3-pip
      - python3-pip-wheel
    pip_packages:
      - ansible
      - pywinrm

  pre_tasks:
    - name: Install system packages
      ansible.builtin.package:
        name: "{{ package }}"
        state: present
      loop: "{{ packages }}"
      loop_control:
        loop_var: package

    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{ pip_package }}"
        state: present
      loop: "{{ pip_packages }}"
      loop_control:
        loop_var: pip_package

    - name: Workaround .NET Core issue
      ansible.builtin.shell:
        cmd: update-crypto-policies --set DEFAULT:SHA1

  roles:
    - role: monolithprojects.github_actions_runner
    - role: monolithprojects.user_management
